### ISSUE TITLE
Set up Firestore in the project

### ISSUE THREAD

**Issue by rock3r** [squanchy-dev/squanchy-flutter#5]
* [x] Create the iOS App configuration on the Firebase console
* [x] Create the Android app configuration on the Firebase console
       _This shares the same configuration as the native Android app so it's already set up._
* [x] Configure the Firestore library using FlutterFire's `cloud_firestore` plugin
* [x] Confirm data can be accessed from the Flutter app (no UI needed)
